53b68b2f6f5c0ac5f5507d61240a7fad2c1523c8
==================================================
Log exceptions when closing the server socket and don't re-throw
==================================================
Mark Thomas
==================================================
Thu Apr 2 21:23:51 2020 +0100
==================================================
NioEndpoint.java
Log exceptions when closing the server socket and don't re-throw

Running the unit tests on MacOS I saw a test failure caused by an
exception as this point. I've never seen an exception here before. It
certainly isn't repeatable. On balance, logging the exception and
completing the rest of the Connector shutdown cleanly looks to be the
better option.


==================================================
